---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ansible-devspaces-demo
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push, pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/task: "[git-clone, pylint]"
    pipelinesascode.tekton.dev/task-1: "[.tekton/tasks/gitleaks.yaml]"
    pipelinesascode.tekton.dev/task-2: "[.tekton/tasks/yaml-lint.yaml]"
    pipelinesascode.tekton.dev/task-3: "[.tekton/tasks/ansible-lint.yaml]"
spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
    workspaces:
      - name: source
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: source
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)

      - name: detect-secrets
        runAfter:
          - fetch-repository
        taskRef:
          name: gitleaks
        workspaces:
          - name: source
            workspace: source
        params:
          - name: config_file_url
            value: https://raw.githubusercontent.com/tektoncd/catalog/main/task/gitleaks/0.1/samples/gitleaks.toml
          - name: config_file_path
            value: gitleaks.toml
          - name: report_output_path
            value: gitleaks-report.json

      - name: yaml-lint
        runAfter:
          - detect-secrets
        taskRef:
          name: yaml-lint
        workspaces:
          - name: source
            workspace: source
        params:
          - name: extra-args
            value: "-c .yamllint ."

      - name: ansible-lint
        runAfter:
          - yaml-lint
        taskRef:
          name: ansible-lint
        workspaces:
          - name: source
            workspace: source

      - name: pylint
        runAfter:
          - ansible-lint
        taskRef:
          name: pylint
        workspaces:
          - name: source
            workspace: source
        params:
          - name: args
            value: ["-r", "y"]
          - name: path
            value: "python/examples"

  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
